import { ExecutorMode, PermissionMode, ToolMetadata } from "../../types.js";
import { summarizeSideEffects } from "./tool-risk.js";

const ALL_MODES: PermissionMode[] = ["read_only", "manual_review", "auto_review", "full_access"];
const WRITE_MODES: PermissionMode[] = ["manual_review", "auto_review", "full_access"];
const ALL_EXECUTORS: ExecutorMode[] = ["webagent", "codex", "hybrid", "external"];

function tool(input: ToolMetadata): ToolMetadata {
  return input;
}

const REGISTRY: ToolMetadata[] = [
  tool({ name: "get_bridge_status", category: "setup", description: "Return bridge runtime status and recent error summary.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "No input.", outputSummary: "Version, modes, counts, recent error, plugin summary.", examples: ["get_bridge_status"] }),
  tool({ name: "get_setup_guide", category: "setup", description: "Return Windows PowerShell and ChatGPT Custom MCP setup guidance.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "No input.", outputSummary: "Dashboard URL, MCP URL, pairing guidance.", examples: ["get_setup_guide"] }),
  tool({ name: "browse_folders", category: "project", description: "Browse local folders for project selection.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "Optional absolute folder path.", outputSummary: "Safe directory list.", examples: ["browse_folders { path }"] }),
  tool({ name: "select_project", category: "project", description: "Register a folder as a project allowlist root.", riskLevel: "medium", sideEffects: ["write"], requiresApproval: false, allowedPermissionModes: WRITE_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "path, displayName, allowShell.", outputSummary: "Project record and projectId.", examples: ["select_project { path }"] }),
  tool({ name: "list_projects", category: "project", description: "List registered projects.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "No input.", outputSummary: "Projects.", examples: ["list_projects"] }),
  tool({ name: "inspect_project", category: "project", description: "Inspect tree, README, package.json, rules, git status, and tech stack.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent", "codex"], inputSummary: "Optional projectId.", outputSummary: "Project inspection summary.", examples: ["inspect_project { projectId }"] }),
  tool({ name: "read_file", category: "project", description: "Read one safe relative file in a registered project.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent", "codex"], inputSummary: "projectId, filePath.", outputSummary: "File metadata and content.", examples: ["read_file { projectId, filePath }"] }),
  tool({ name: "index_project", category: "context", description: "Create or refresh a token-conscious FTS project index.", riskLevel: "low", sideEffects: ["write"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "projectId, force.", outputSummary: "Index manifest.", examples: ["index_project { projectId, force: true }"] }),
  tool({ name: "get_index_status", category: "context", description: "Read project context index status.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "projectId.", outputSummary: "Index status.", examples: ["get_index_status { projectId }"] }),
  tool({ name: "search_project", category: "context", description: "Search indexed project context and snippets.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "projectId, query, limit.", outputSummary: "Concise search matches.", examples: ["search_project { projectId, query }"] }),
  tool({ name: "retrieve_context", category: "context", description: "Retrieve a small relevant context bundle instead of full files.", riskLevel: "low", sideEffects: ["read", "write"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent", "codex"], inputSummary: "projectId, optional task/taskBranch, query, budget limits.", outputSummary: "Retrieved context record with snippets and next reads.", examples: ["retrieve_context { projectId, taskBranchId, query }"] }),
  tool({ name: "refresh_context_index", category: "context", description: "Force-refresh the project context index.", riskLevel: "low", sideEffects: ["write"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "projectId.", outputSummary: "Index manifest.", examples: ["refresh_context_index { projectId }"] }),
  tool({ name: "create_context_pack", category: "context", description: "Create a bounded context pack from retrieval and optional file excerpts.", riskLevel: "medium", sideEffects: ["read", "write"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent", "codex"], inputSummary: "projectId, task/taskBranch, goal, paths, budget.", outputSummary: "Context pack id, path, summary, markdown.", examples: ["create_context_pack { projectId, taskBranchId, budget: 'small' }"] }),
  tool({ name: "create_task", category: "task", description: "Create a project task and default Task Branch.", riskLevel: "low", sideEffects: ["write"], requiresApproval: false, allowedPermissionModes: WRITE_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "projectId, goal, executor hints, target files.", outputSummary: "Task, default branch, routing decision.", examples: ["create_task { projectId, taskGoal }"] }),
  tool({ name: "list_tasks", category: "task", description: "List tasks.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "Optional projectId.", outputSummary: "Tasks.", examples: ["list_tasks { projectId }"] }),
  tool({ name: "get_task", category: "task", description: "Read one task and linked artifacts.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "taskId.", outputSummary: "Task detail.", examples: ["get_task { taskId }"] }),
  tool({ name: "continue_task", category: "task", description: "Continue a task from MCP-backed state.", riskLevel: "low", sideEffects: ["read", "write"], requiresApproval: false, allowedPermissionModes: WRITE_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "taskId, optional taskBranchId, note, createContextPack.", outputSummary: "Current task state, runId, next action.", examples: ["continue_task { taskId, taskBranchId }"] }),
  tool({ name: "create_task_branch", category: "taskBranch", description: "Create a Task Branch for a separate ChatGPT conversation.", riskLevel: "low", sideEffects: ["write"], requiresApproval: false, allowedPermissionModes: WRITE_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "taskId, branch name/goal, touched files.", outputSummary: "Task Branch record.", examples: ["create_task_branch { taskId, branchName }"] }),
  tool({ name: "list_task_branches", category: "taskBranch", description: "List Task Branches by project or task.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "Optional projectId/taskId.", outputSummary: "Task Branch records.", examples: ["list_task_branches { taskId }"] }),
  tool({ name: "get_task_branch", category: "taskBranch", description: "Read one Task Branch and linked state.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "taskBranchId.", outputSummary: "Branch, task, context and patches.", examples: ["get_task_branch { taskBranchId }"] }),
  tool({ name: "continue_task_branch", category: "taskBranch", description: "Continue one Task Branch and create a run timeline.", riskLevel: "low", sideEffects: ["read", "write"], requiresApproval: false, allowedPermissionModes: WRITE_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "taskBranchId, note, createContextPack.", outputSummary: "Run id, branch state, next action.", examples: ["continue_task_branch { taskBranchId }"] }),
  tool({ name: "rename_task_branch", category: "taskBranch", description: "Rename a Task Branch.", riskLevel: "low", sideEffects: ["write"], requiresApproval: false, allowedPermissionModes: WRITE_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "taskBranchId, branchName, chatTitleHint.", outputSummary: "Updated branch.", examples: ["rename_task_branch { taskBranchId, branchName }"] }),
  tool({ name: "archive_task_branch", category: "taskBranch", description: "Archive a Task Branch without deleting history.", riskLevel: "medium", sideEffects: ["write"], requiresApproval: false, allowedPermissionModes: WRITE_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "taskBranchId.", outputSummary: "Archived branch.", examples: ["archive_task_branch { taskBranchId }"] }),
  tool({ name: "set_active_task_branch", category: "taskBranch", description: "Set active branch for a task.", riskLevel: "low", sideEffects: ["write"], requiresApproval: false, allowedPermissionModes: WRITE_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "taskId, taskBranchId.", outputSummary: "Updated task.", examples: ["set_active_task_branch { taskId, taskBranchId }"] }),
  tool({ name: "detect_branch_conflicts", category: "taskBranch", description: "Detect overlapping files and stale git head across active branches.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "taskBranchId.", outputSummary: "Conflict summary.", examples: ["detect_branch_conflicts { taskBranchId }"] }),
  tool({ name: "recommend_isolation_mode", category: "taskBranch", description: "Recommend in_place, git_worktree, or copy_workspace for a Task Branch.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ALL_EXECUTORS, inputSummary: "taskBranchId or executor/complexity hints.", outputSummary: "Isolation recommendation and risk notes.", examples: ["recommend_isolation_mode { taskBranchId }"] }),
  tool({ name: "create_task_worktree", category: "taskBranch", description: "Create an optional git worktree or copy workspace for one Task Branch.", riskLevel: "high", sideEffects: ["write", "git"], requiresApproval: true, allowedPermissionModes: ["manual_review", "auto_review", "full_access"], recommendedExecutorModes: ["codex", "hybrid", "external"], inputSummary: "taskBranchId, optional isolationMode.", outputSummary: "Workspace path and worktree status.", examples: ["create_task_worktree { taskBranchId, isolationMode: 'git_worktree' }"] }),
  tool({ name: "get_task_worktree_status", category: "taskBranch", description: "Read Task Branch isolation/worktree status.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ALL_EXECUTORS, inputSummary: "taskBranchId.", outputSummary: "Isolation fields and filesystem status.", examples: ["get_task_worktree_status { taskBranchId }"] }),
  tool({ name: "cleanup_task_worktree", category: "taskBranch", description: "Cleanup an isolated workspace or git worktree.", riskLevel: "critical", sideEffects: ["write", "git"], requiresApproval: true, allowedPermissionModes: ["manual_review", "auto_review", "full_access"], recommendedExecutorModes: ["codex", "hybrid", "external"], inputSummary: "taskBranchId, confirm.", outputSummary: "Cleanup status.", examples: ["cleanup_task_worktree { taskBranchId, confirm: true }"] }),
  tool({ name: "propose_web_patch", category: "patch", description: "Create a bounded patch draft without writing files.", riskLevel: "medium", sideEffects: ["write"], requiresApproval: false, allowedPermissionModes: WRITE_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "projectId, task/taskBranch, title, changes.", outputSummary: "Patch draft with conflict status.", examples: ["propose_web_patch { projectId, taskBranchId, changes }"] }),
  tool({ name: "get_patch_diff", category: "patch", description: "Return readable diff for a patch draft.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent", "codex"], inputSummary: "patchId.", outputSummary: "Diff text.", examples: ["get_patch_diff { patchId }"] }),
  tool({ name: "get_patch_conflict_status", category: "patch", description: "Return stale-base and Task Branch conflict status.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent", "codex"], inputSummary: "patchId.", outputSummary: "Conflict status.", examples: ["get_patch_conflict_status { patchId }"] }),
  tool({ name: "preflight_patch_apply", category: "patch", description: "Run full patch apply preflight without writing files.", riskLevel: "medium", sideEffects: ["read", "write"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent", "codex"], inputSummary: "patchId.", outputSummary: "Patch safety report.", examples: ["preflight_patch_apply { patchId }"] }),
  tool({ name: "request_apply_patch", category: "patch", description: "Request or perform guarded patch apply after preflight.", riskLevel: "high", sideEffects: ["write"], requiresApproval: true, allowedPermissionModes: WRITE_MODES, recommendedExecutorModes: ["webagent", "codex"], inputSummary: "patchId.", outputSummary: "Patch safety report, approval info, or apply result.", examples: ["request_apply_patch { patchId }"] }),
  tool({ name: "request_revert_patch", category: "patch", description: "Request or perform guarded patch revert from backups.", riskLevel: "high", sideEffects: ["write"], requiresApproval: true, allowedPermissionModes: ["manual_review", "auto_review", "full_access"], recommendedExecutorModes: ["webagent", "codex"], inputSummary: "patchId.", outputSummary: "Revert result or approval info.", examples: ["request_revert_patch { patchId }"] }),
  tool({ name: "run_shell_command", category: "shell", description: "Create and optionally run a guarded shell command.", riskLevel: "critical", sideEffects: ["shell", "write"], requiresApproval: true, allowedPermissionModes: ["manual_review", "auto_review", "full_access"], recommendedExecutorModes: ["codex", "hybrid"], inputSummary: "projectId, command, cwd, timeout, shell.", outputSummary: "Shell command record, approval info, stdout/stderr when run.", examples: ["run_shell_command { projectId, command: 'git status', runImmediately: true }"] }),
  tool({ name: "create_execution_job", category: "executor", description: "Create an executor job and run timeline.", riskLevel: "high", sideEffects: ["write", "external"], requiresApproval: true, allowedPermissionModes: ["manual_review", "auto_review", "full_access"], recommendedExecutorModes: ALL_EXECUTORS, inputSummary: "taskId, taskBranchId, executorMode, runImmediately.", outputSummary: "Execution job with runId.", examples: ["create_execution_job { taskId, taskBranchId, executorMode: 'webagent' }"] }),
  tool({ name: "get_execution_job", category: "executor", description: "Read one execution job.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ALL_EXECUTORS, inputSummary: "jobId.", outputSummary: "Execution job.", examples: ["get_execution_job { jobId }"] }),
  tool({ name: "list_runs", category: "logs", description: "List Agent Run records.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "Optional projectId/taskId/taskBranchId/status/limit.", outputSummary: "Runs.", examples: ["list_runs { taskBranchId }"] }),
  tool({ name: "get_run", category: "logs", description: "Read one Agent Run and recent events.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "runId.", outputSummary: "Run record and events.", examples: ["get_run { runId }"] }),
  tool({ name: "get_run_events", category: "logs", description: "Read runtime events for one run or filtered scope.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "runId or filters.", outputSummary: "Runtime event timeline.", examples: ["get_run_events { runId }"] }),
  tool({ name: "cancel_run", category: "admin", description: "Mark a run cancelled and attempt best-effort process cancellation.", riskLevel: "medium", sideEffects: ["write"], requiresApproval: false, allowedPermissionModes: WRITE_MODES, recommendedExecutorModes: ALL_EXECUTORS, inputSummary: "runId, reason.", outputSummary: "Cancelled run and limitation notes.", examples: ["cancel_run { runId }"] }),
  tool({ name: "get_latest_logs", category: "logs", description: "Read recent audit logs with filters.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "Optional level, requestId, projectId, taskId, taskBranchId, runId, limit.", outputSummary: "Log entries.", examples: ["get_latest_logs { requestId }"] }),
  tool({ name: "analyze_error_log", category: "logs", description: "Analyze a matching error log and suggest next actions.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "requestId or logId.", outputSummary: "Error analysis.", examples: ["analyze_error_log { requestId }"] }),
  tool({ name: "create_repair_proposal", category: "repair", description: "Create a repair proposal that does not execute automatically.", riskLevel: "medium", sideEffects: ["write"], requiresApproval: true, allowedPermissionModes: WRITE_MODES, recommendedExecutorModes: ["webagent", "codex"], inputSummary: "Diagnosis, solution, execution plan.", outputSummary: "Repair proposal.", examples: ["create_repair_proposal { errorSummary, solution, executionPlan }"] }),
  tool({ name: "create_ui_screenshot_job", category: "ui", description: "Create a UI screenshot review job.", riskLevel: "medium", sideEffects: ["write", "network"], requiresApproval: false, allowedPermissionModes: WRITE_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "projectId, devServerUrl, route, notes.", outputSummary: "Execution job.", examples: ["create_ui_screenshot_job { projectId, devServerUrl }"] }),
  tool({ name: "get_ui_screenshot_result", category: "ui", description: "Read UI screenshot job result.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "jobId.", outputSummary: "Execution job result.", examples: ["get_ui_screenshot_result { jobId }"] }),
  tool({ name: "create_cross_review", category: "review", description: "Open a bounded WebAgent/Codex cross review.", riskLevel: "medium", sideEffects: ["write"], requiresApproval: false, allowedPermissionModes: WRITE_MODES, recommendedExecutorModes: ["hybrid"], inputSummary: "projectId, taskId, title, patch/job ids.", outputSummary: "Review session.", examples: ["create_cross_review { projectId, title }"] }),
  tool({ name: "add_cross_review_round", category: "review", description: "Add one bounded review round.", riskLevel: "low", sideEffects: ["write"], requiresApproval: false, allowedPermissionModes: WRITE_MODES, recommendedExecutorModes: ["hybrid"], inputSummary: "reviewId, speaker, issues, evidence, decision.", outputSummary: "Updated review.", examples: ["add_cross_review_round { reviewId, recommendedDecision }"] }),
  tool({ name: "finalize_cross_review", category: "review", description: "Finalize a bounded cross review.", riskLevel: "low", sideEffects: ["write"], requiresApproval: false, allowedPermissionModes: WRITE_MODES, recommendedExecutorModes: ["hybrid"], inputSummary: "reviewId, decision, rationale.", outputSummary: "Final review.", examples: ["finalize_cross_review { reviewId, decision }"] }),
  tool({ name: "create_webagent_task", category: "task", description: "Shortcut to create a WebAgent task and execution job.", riskLevel: "medium", sideEffects: ["write"], requiresApproval: false, allowedPermissionModes: WRITE_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "projectId, taskGoal, targetFiles.", outputSummary: "Task and execution.", examples: ["create_webagent_task { projectId, taskGoal }"] }),
  tool({ name: "create_codex_job", category: "executor", description: "Legacy alias for Codex execution job.", riskLevel: "high", sideEffects: ["write", "external"], requiresApproval: true, allowedPermissionModes: ["manual_review", "auto_review", "full_access"], recommendedExecutorModes: ["codex"], inputSummary: "taskId, runImmediately.", outputSummary: "Execution job.", examples: ["create_codex_job { taskId }"] }),
  tool({ name: "get_codex_job", category: "executor", description: "Legacy alias for reading one execution job.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["codex"], inputSummary: "jobId.", outputSummary: "Execution job.", examples: ["get_codex_job { jobId }"] }),
  tool({ name: "get_tool_registry", category: "admin", description: "Return Tool Registry metadata.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "Optional category.", outputSummary: "Tool metadata list.", examples: ["get_tool_registry"] }),
  tool({ name: "get_tool_policy", category: "admin", description: "Return approval policy summary for tools/actions.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "Optional toolName.", outputSummary: "Permission and approval policy.", examples: ["get_tool_policy { toolName }"] }),
  tool({ name: "explain_tool_risk", category: "admin", description: "Explain risk and side effects for one tool.", riskLevel: "low", sideEffects: ["read"], requiresApproval: false, allowedPermissionModes: ALL_MODES, recommendedExecutorModes: ["webagent"], inputSummary: "toolName.", outputSummary: "Risk explanation.", examples: ["explain_tool_risk { toolName: 'request_apply_patch' }"] })
];

export class ToolRegistry {
  list(category?: ToolMetadata["category"]): ToolMetadata[] {
    return REGISTRY.filter((tool) => !category || tool.category === category).sort((a, b) => a.name.localeCompare(b.name));
  }

  get(name: string): ToolMetadata | undefined {
    return REGISTRY.find((tool) => tool.name === name);
  }

  explain(name: string) {
    const tool = this.get(name);
    if (!tool) throw new Error("tool not found in registry");
    return {
      tool,
      summary: `${tool.name} is ${tool.riskLevel} risk: ${summarizeSideEffects(tool.sideEffects)}.`,
      approvalGuidance: tool.requiresApproval
        ? "Callers should expect an approvalId or approvalRequired response before side effects proceed."
        : "This tool is normally allowed without manual approval under supported permission modes."
    };
  }
}

